### ISSUE TITLE
Issues in Retriving the Image

### ISSUE THREAD

**Issue by shreegowtham27** [robincsamuel/ghost-google-drive#31]
Hello Team,

The following question is from some other User. (Adding here, Since I am also facing the same)

I think I am close to getting ghost-google-drive to work, but having a couple of issues. I have installed the adapter on my local Ghost instance, obtained the proper API configuration from console.cloud.google.com 2 and loaded it into config.production.json, and tested a few images. However, two issues I am seeing:

1.  My images are not uploading to the GDrive but are being stored locally. However, I can see the API requests on the Google Console for methods drive.files.get and drive.files.insert with response code 200. The images appear to be getting hashed names, but they are going into my local content/images/ folder (e.g. 192.168.1.106:2368/content/images/17RDvT9swQJ0ixLu3aDM0BdJYsJD4CNbb.jpg) and not content/images/YYYY/MM like the base storage adapter normally does–that makes me thing the ghost-google-drive adapter is doing something. Is this indeed processing on via Google APIs then storing locally? I cannot find the files on the GDrive, 
    
    
 2. Where can I view these images if they have uploaded to google drive? I cannot see any files in my personal GDrive associated with the cloud. google login (though they may not be uploading). This is the only Google Drive I can find, is it the correct one? If it is the right one, is it safe to assume the files are indeed not uploading despite seeing the API requests from above?

What are some next steps I can use to debug or test what’s happening here? Am I missing something? Would I be able to provide anything else here to help resolve this?

Thank you!

**Comment by robincsamuel** [comment]
Hi @shreegowtham27 

Though the storage adapter makes API calls and stores the images on google drive, the URL still looks like a local one. It's because the only thing the storage adapter needs is the file id. You'll understand this if you look at the source code were the file id is extracted from the local URL and the file is downloaded and served as the response.

The storage adapter is working like an interceptor. 

Also, you cannot see the images uploaded in your google drive, as the service account is a different one. Please see [this comment](https://github.com/robincsamuel/ghost-google-drive/issues/21#issuecomment-573515450)
